//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seven7c.OA.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class R_UserInfo_ActionInfo
    {
        public int Id { get; set; }
        public bool IsPass { get; set; }
        public int UserInfoId { get; set; }
        public int ActionInfoId { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
        public virtual ActionInfo ActionInfo { get; set; }
    }
}
