//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seven7c.OA.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class WF_Step
    {
        public int Id { get; set; }
        public int WF_InstanceId { get; set; }
        public string StepName { get; set; }
        public Nullable<int> ProcessBy { get; set; }
        public short Status { get; set; }
        public bool IsStartStep { get; set; }
        public bool IsEndStep { get; set; }
        public string Result { get; set; }
        public string Comment { get; set; }
        public System.DateTime SubTime { get; set; }
        public Nullable<System.DateTime> CheckTime { get; set; }
        public short DelFlag { get; set; }
        public string Remark { get; set; }
    
        public virtual WF_Instance WF_Instance { get; set; }
    }
}
